name: lightRAG
channels:
  - defaults
  - conda-forge
dependencies:
  - aiohttp
  - configparser
  - future
  - gensim
  - pandas>=2.0.0
  - pip
  - setuptools
  - tenacity
  - tiktoken
  - xlsxwriter>=3.1.0
  - pip:
      - pipmaster
      - pydantic
      - python-dotenv
